import { motion } from "framer-motion";
import { usePageTitle } from "../../hooks/usePageTitle";

export default function DisclaimerPage() {
  usePageTitle({
    title: "Disclaimer | TexIntelli",
    description: "Read the legal disclaimer regarding the information and services provided by TexIntelli."
  });

  return (
    <div className="min-h-screen bg-gray-50">
      <section className="max-w-6xl mx-auto py-16 px-6">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6 }}
          className="space-y-12 text-gray-700"
        >
          {/* Page Title */}
          <div className="text-center mb-10">
            <h1 className="text-4xl md:text-5xl font-extrabold text-gray-900 mb-4">
              Disclaimer
            </h1>
            <p className="text-lg text-gray-600 max-w-3xl mx-auto">
              Please read this disclaimer carefully before using the TexIntelli platform operated by Dhya Innovations Private Limited.
            </p>
          </div>

          {/* Disclaimer Sections */}
          <div className="space-y-10">

            {/* 1. No Professional Advice */}
            <div className="bg-white p-6 rounded-xl shadow-sm hover:shadow-md transition">
              <h2 className="text-2xl font-bold text-gray-900 mb-3">
                1. No Professional Advice
              </h2>
              <p className="leading-relaxed">
                The information, data, reports, and recommendations provided by TexIntelli are intended for general informational purposes only.
                They do not constitute professional, financial, business, or legal advice. Users are encouraged to seek independent professional consultation where required.
              </p>
            </div>

            {/* 2. Accuracy of Information */}
            <div className="bg-white p-6 rounded-xl shadow-sm hover:shadow-md transition">
              <h2 className="text-2xl font-bold text-gray-900 mb-3">
                2. Accuracy of Information
              </h2>
              <p className="leading-relaxed">
                While we strive to ensure the accuracy and reliability of data generated by TexIntelli, 
                we do not guarantee that all content is always accurate, complete, or updated.
                Dhya Innovations is not responsible for any errors, omissions, or consequences arising from use of the platform.
              </p>
            </div>

            {/* 3. Limitation of Liability */}
            <div className="bg-white p-6 rounded-xl shadow-sm hover:shadow-md transition">
              <h2 className="text-2xl font-bold text-gray-900 mb-3">
                3. Limitation of Liability
              </h2>
              <p className="leading-relaxed">
                Under no circumstances shall Dhya Innovations Private Limited, its directors, employees, or affiliates 
                be liable for any indirect, incidental, consequential, or special damages arising out of the use of TexIntelli.
              </p>
            </div>

            {/* 4. External Links Disclaimer */}
            <div className="bg-white p-6 rounded-xl shadow-sm hover:shadow-md transition">
              <h2 className="text-2xl font-bold text-gray-900 mb-3">
                4. External Links Disclaimer
              </h2>
              <p className="leading-relaxed">
                TexIntelli may contain links to external websites or third-party resources. 
                We do not endorse or assume any responsibility for their content, accuracy, or practices.
                Users should exercise caution when visiting external sites.
              </p>
            </div>

            {/* 5. Changes to Disclaimer */}
            <div className="bg-white p-6 rounded-xl shadow-sm hover:shadow-md transition">
              <h2 className="text-2xl font-bold text-gray-900 mb-3">
                5. Changes to This Disclaimer
              </h2>
              <p className="leading-relaxed">
                We reserve the right to modify this Disclaimer at any time without prior notice.
                It is your responsibility to review this page periodically.
                Continued use of TexIntelli following changes indicates acceptance of the updated Disclaimer.
              </p>
            </div>

            {/* 6. Contact Us */}
            <div className="bg-white p-6 rounded-xl shadow-sm hover:shadow-md transition">
              <h2 className="text-2xl font-bold text-gray-900 mb-3">
                6. Contact Information
              </h2>
              <p className="leading-relaxed">
                If you have any questions about this Disclaimer, please contact us:
              </p>
              <ul className="mt-4 space-y-2 text-blue-600">
                <li>Email: <a href="mailto:support@dhya.in" className="hover:underline">support@dhya.in</a></li>
              </ul>
            </div>

          </div>
        </motion.div>
      </section>
    </div>
  );
}